local PickerState = require('telescope-orgmode.lib.state')

describe('[Unit: lib/state]', function()
  describe('initialization', function()
    it('initializes with headlines mode', function()
      local state = PickerState:new('headlines')
      assert.equals('headlines', state:get_current())
    end)

    it('initializes with orgfiles mode', function()
      local state = PickerState:new('orgfiles')
      assert.equals('orgfiles', state:get_current())
    end)
  end)

  describe('mode toggling', function()
    it('toggles between modes', function()
      local state = PickerState:new('headlines')
      state:toggle()
      assert.equals('orgfiles', state:get_current())
      state:toggle()
      assert.equals('headlines', state:get_current())
    end)

    it('preserves filters when toggling', function()
      local state = PickerState:new('headlines')
      state:set_filter('only_current_file', true)
      state:set_filter('archived', false)
      state:toggle()
      assert.is_true(state:get_filter('only_current_file'))
      assert.is_false(state:get_filter('archived'))
    end)
  end)

  describe('filter management', function()
    it('sets and gets individual filters', function()
      local state = PickerState:new('headlines')
      state:set_filter('max_depth', 3)
      assert.equals(3, state:get_filter('max_depth'))
    end)

    it('returns all filters', function()
      local state = PickerState:new('headlines')
      state:set_filter('only_current_file', true)
      state:set_filter('max_depth', 2)
      local filters = state:get_all_filters()
      assert.is_true(filters.only_current_file)
      assert.equals(2, filters.max_depth)
    end)

    it('handles nil filter keys', function()
      local state = PickerState:new('headlines')
      assert.is_nil(state:get_filter('nonexistent'))
    end)
  end)
end)
