local PickerState = require('telescope-orgmode.lib.state')

describe('[Unit: lib/state]', function()
  describe('initialization', function()
    it('initializes with headlines mode', function()
      local state = PickerState:new('headlines')
      assert.equals('headlines', state:get_current())
    end)

    it('initializes with orgfiles mode', function()
      local state = PickerState:new('orgfiles')
      assert.equals('orgfiles', state:get_current())
    end)
  end)

  describe('mode toggling', function()
    it('toggles between modes', function()
      local state = PickerState:new('headlines')
      state:toggle()
      assert.equals('orgfiles', state:get_current())
      state:toggle()
      assert.equals('headlines', state:get_current())
    end)

    it('preserves filters when toggling', function()
      local state = PickerState:new('headlines')
      state:set_filter('only_current_file', true)
      state:set_filter('archived', false)
      state:toggle()
      assert.is_true(state:get_filter('only_current_file'))
      assert.is_false(state:get_filter('archived'))
    end)
  end)

  describe('filter management', function()
    it('sets and gets individual filters', function()
      local state = PickerState:new('headlines')
      state:set_filter('max_depth', 3)
      assert.equals(3, state:get_filter('max_depth'))
    end)

    it('returns all filters', function()
      local state = PickerState:new('headlines')
      state:set_filter('only_current_file', true)
      state:set_filter('max_depth', 2)
      local filters = state:get_all_filters()
      assert.is_true(filters.only_current_file)
      assert.equals(2, filters.max_depth)
    end)

    it('handles nil filter keys', function()
      local state = PickerState:new('headlines')
      assert.is_nil(state:get_filter('nonexistent'))
    end)
  end)

  describe('get_title_context', function()
    it('returns empty string when no filters active', function()
      local state = PickerState:new('headlines')
      assert.equals('', state:get_title_context())
    end)

    it('shows tag filter when tag_query is set', function()
      local state = PickerState:new('headlines')
      state:set_filter('tag_query', '+work')
      assert.equals('[tag:+work]', state:get_title_context())
    end)

    it('shows file filter when only_current_file is true', function()
      local state = PickerState:new('headlines')
      state:set_filter('only_current_file', true)
      state:set_filter('current_file', '/path/to/todo.org')
      assert.equals('[file:todo.org]', state:get_title_context())
    end)

    it('shows no-archive when archived explicitly disabled', function()
      local state = PickerState:new('headlines')
      state:set_filter('archived', false)
      assert.equals('[no-archive]', state:get_title_context())
    end)

    it('shows max_depth when set', function()
      local state = PickerState:new('headlines')
      state:set_filter('max_depth', 3)
      assert.equals('[depth:3]', state:get_title_context())
    end)

    it('combines multiple filters with space separator', function()
      local state = PickerState:new('headlines')
      state:set_filter('tag_query', '+work')
      state:set_filter('only_current_file', true)
      state:set_filter('current_file', '/path/to/todo.org')
      state:set_filter('max_depth', 2)
      assert.equals('[tag:+work] [file:todo.org] [depth:2]', state:get_title_context())
    end)

    it('extracts filename from full path', function()
      local state = PickerState:new('headlines')
      state:set_filter('only_current_file', true)
      state:set_filter('current_file', '/home/user/documents/notes/work.org')
      assert.equals('[file:work.org]', state:get_title_context())
    end)

    it('handles current_file fallback when not set', function()
      local state = PickerState:new('headlines')
      state:set_filter('only_current_file', true)
      -- current_file not set, should use 'current' as fallback
      assert.equals('[file:current]', state:get_title_context())
    end)

    it('ignores max_depth when zero', function()
      local state = PickerState:new('headlines')
      state:set_filter('max_depth', 0)
      assert.equals('', state:get_title_context())
    end)

    it('does not show archived filter when true (default)', function()
      local state = PickerState:new('headlines')
      state:set_filter('archived', true)
      assert.equals('', state:get_title_context())
    end)
  end)
end)
